### ISSUE TITLE
Сообщение No reCAPTCHA clients exist

### ISSUE THREAD

**Issue by SoftAlex** [ig0r74/reCaptchaV3#1]
После отправки формы в консоле хрома выскакивает сообщение. Поиск проблемы и решения не дал результатов. На демо сайте такая же ошибка.

`No reCAPTCHA clients exist.`

**Comment by Element1493** [comment]
То же самое.

**Comment by search2074** [comment]
Тут всегда 0.
![image](https://user-images.githubusercontent.com/7188152/71653999-2683e380-2d51-11ea-8619-3594bd66f6c6.png)
Поэтому и исключение вылетает.
