### ISSUE TITLE
Мы обнаружили, что ваш сайт не проверяет токены reCAPTCHA.

### ISSUE THREAD

**Issue by Batyabest** [ig0r74/reCaptchaV3#6]
Добрый день.
Google выдает предупреждение:
"Мы обнаружили, что ваш сайт не проверяет токены reCAPTCHA."
При этом на сайте формы не отправляются - пишет что форма содержит ошибку....

**Comment by ig0r74** [comment]
Здравствуйте, скиньте вызов формы.

**Comment by Batyabest** [comment]
Добрый день.

`{'!AjaxForm' | snippet : [
    'snippet' => 'FormIt',
    'form' => '@FILE chunks/form1.html',
    'emailTpl' => '@FILE chunks/form_send.html',
    'hooks' => 'rcv3,email',
    'emailSubject' => 'Заявка с сайта',
    'emailTo' => 'info@site.ru',
    'emailFrom' => 'noreply@site.ru',
    'validate' => 'name:required,phone:required',
    'validationErrorMessage' => 'В форме содержатся ошибки!',
    'successMessage' => 'Сообщение успешно отправлено',
    ]}`

**Comment by Batyabest** [comment]
Добрый день. Стоит ожидать какого-то решения?

**Comment by ig0r74** [comment]
> Добрый день. Стоит ожидать какого-то решения?

Добрый день, уведомление не прилетело на предыдущее сообщение. Еще код формы забыли скинуть.

**Comment by Batyabest** [comment]
Ага, не заметил про форму:

`<form action="" method="post" id="form1">
    <input name="name" type="text" value="[[+fi.name]]" placeholder="Ваше имя" required>
    <input name="phone" type="tel" value="[[+fi.phone]]" placeholder="Ваш телефон" required>
    <input name="email" type="text" value="[[+fi.email]]" placeholder="Ваш E-mail" required>
    <textarea name="message" placeholder="Ваше сообщение"></textarea>
    <button type="submit">Оставить заявку</button>
    <div class="form__polit">Нажимая кнопку, ты разрешаешь обработку персональных данных и соглашаешься с <a href="#" target="_blank">политикой конфиденциальности.</a></div>
    {'!rcv3_html' | snippet : [
    'action' => $rcv3Action,
    'error' => $_modx->getPlaceholder('fi.error.g-recaptcha-response'),
    ]}
</form>`

**Comment by Batyabest** [comment]
Чет съедает тег форм)

`<form action="" method="post" id="form1">`

**Comment by Batyabest** [comment]
В консоли нет ошибок, но такое ощущение что каптча вообще не подключилась, шильдика нет справа снизу...

**Comment by ig0r74** [comment]
> В консоли нет ошибок, но такое ощущение что каптча вообще не подключилась, шильдика нет справа снизу...

Компонент ставили с [modstore.pro](https://modstore.pro/packages/utilities/recaptchav3)?
Ключи указали в системных настройках?
Есть что-то в журнале ошибок MODX?

**Comment by Batyabest** [comment]
Да, ключи прописаны, журнал молчит...

**Comment by Batyabest** [comment]
Компонент да, с modstore ставил

**Comment by ig0r74** [comment]
> Компонент да, с modstore ставил

У меня только последний вариант остался :) Ключи от какой версии капчи?

**Comment by Batyabest** [comment]
Версии 3 ))
Я могу дать доступ к сайту, потому что честно говоря ни разу с такой проблемой не сталкивался...

**Comment by Batyabest** [comment]
Такое ощущение что каптча вообще работать перестала... Массово летит спам с многих сайтов. И везде гугл пишет: Мы обнаружили, что ваш сайт не проверяет токены reCAPTCHA.

**Comment by ig0r74** [comment]
Значит что-то со стороны google, потому что у меня все ок и таких жалоб не было. Попробуйте пересоздать ключ.

**Comment by Batyabest** [comment]
В логах при отправке формы вот что

> [2021-11-17 19:45:16] (ERROR @ /core/cache/includes/elements/modsnippet/21.include.cache.php : 30) Data Google API ERRORS:<br/>

**Comment by ig0r74** [comment]
Ок, если удастся разобраться и дело в компоненте - отправляй pull-request.
