### ISSUE TITLE
Плагин не делает скоринг.

### ISSUE THREAD

**Issue by FETWEB** [ig0r74/reCaptchaV3#7]
![изображение](https://user-images.githubusercontent.com/42625943/186927810-19890a5a-7861-415d-b472-ab2d04c58108.png)

Плагин не делает скоринг, а просто проверяет - был ли этот запрос действительным токеном reCAPTCHA для вашего сайта.

Для того чтобы был скоринг надо
`if($data->success && $data->score > 0.5)`
Ниже скрин из доков, того что в JSON ответе приходит
![изображение](https://user-images.githubusercontent.com/42625943/186929366-62e89382-a371-4e85-a78f-38e2f454958d.png)
Ссылка на документацию - https://developers.google.com/recaptcha/docs/v3#site_verify_response

**Comment by ig0r74** [comment]
@alexsoin Спасибо, залил в modstore.
